version: "3"
services:
  db:
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/docker/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changethis
      - POSTGRES_DB=mattermost
  app:
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=admin
      - MM_PASSWORD=changethis
      - MM_DBNAME=mattermost
  web:
    volumes:
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
